### ISSUE TITLE
Regression in version 3.4.0-pre1: Cannot find module `cable_ready`

### ISSUE THREAD

**Issue by gordysc** [hopsoft/stimulus_reflex#350]
# Bug Report

## Describe the bug

Following the [Setup](https://docs.stimulusreflex.com/setup#command-line-install) directions for an existing Rails 6 application results in a compilation error by webpacker:

```sh
Webpacker] Compiling...
[Webpacker] Compilation failed:
Hash: d5b1502eaad6860e5fa2
Version: webpack 4.44.2
Time: 633ms
Built at: 11/04/2020 1:48:41 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-18891e9e1fc64378ff3b.js    267 KiB  application  [emitted] [immutable]  application
js/application-18891e9e1fc64378ff3b.js.map    266 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              
Entrypoint application = js/application-18891e9e1fc64378ff3b.js js/application-18891e9e1fc64378ff3b.js.map
[./app/javascript/channels sync recursive _channel\.js$] ./app/javascript/channels sync _channel\.js$ 160 bytes {application} [built]
[./app/javascript/channels/consumer.js] 265 bytes {application} [built]
[./app/javascript/channels/index.js] 211 bytes {application} [built]
[./app/javascript/controllers sync recursive _controller\.js$] ./app/javascript/controllers sync _controller\.js$ 246 bytes {application} [built]
[./app/javascript/controllers/application_controller.js] 4.34 KiB {application} [built]
[./app/javascript/controllers/example_controller.js] 2.48 KiB {application} [optional] [built]
[./app/javascript/controllers/hello_controller.js] 3.26 KiB {application} [optional] [built]
[./app/javascript/controllers/index.js] 646 bytes {application} [built]
[./app/javascript/packs/application.js] 773 bytes {application} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {application} [built]
    + 37 hidden modules

ERROR in ./node_modules/stimulus_reflex/dist/stimulus_reflex.module.js
Module not found: Error: Can't resolve 'cable_ready' in '/<path has been omitted>/node_modules/stimulus_reflex/dist'
 @ ./node_modules/stimulus_reflex/dist/stimulus_reflex.module.js 4:0-28 287:49-50 307:131-132
 @ ./app/javascript/controllers/index.js
 @ ./app/javascript/packs/application.js
```

## To Reproduce

Follow the commands from the [Setup Section](https://docs.stimulusreflex.com/setup#command-line-install):

```sh
# For existing projects
bundle exec rails webpacker:install:stimulus

# For both project types
bundle add stimulus_reflex
bundle exec rails stimulus_reflex:install
```

## Expected behavior

Webpacker should compile without any errors.  This works fine w/ NPM package `stimulus_reflex` version 3.3.0 so it appears the issue was introduced in the 3.4.0-preX version.

## Screenshots or reproduction

_None_

### StimulusReflex

- Gem: 3.2.3
- Node package: 3.4.0-pre1

**Note:** This works fine in 3.3.0.

### External tools

- Ruby: 2.6.6
- Rails: '~> 6.0.3', '>= 6.0.3.4'
- Node: 14.15.0

### Browser

Webpacker compilation error, so the browser doesn't matter

**Comment by marcoroth** [comment]
Hey @gordysc, thanks for reporting this issue!

I think I experienced something similar yesterday but thought it's a local setup thing.

Could you try to `cd node_modules/stimulus_reflex && yarn install && cd -` and see if this resolves the issue for you?

If so, I think we might have to build the npm package differently ;)

**Comment by gordysc** [comment]
@marcoroth Thanks for the fast response!  That did appear to fix the issue as a temporary work around.  In my Rails application I also had to stomp `tmp` and `public/packs`.

**Comment by marcoroth** [comment]
Hey @gordysc, I'm glad that the workaround worked out for you.
 
May I ask, do you have `cable_ready` listed as a dependency in your `package.json`?
If not: running `yarn add cable_ready@4.4.0-pre2` should resolve your issue. 

In #315 `cable_ready` was declared as a peer dependency instead of a regular dependency. As a consequence of this all StimulusReflex apps upgrading from `3.3.x` to `3.4.x` now need to declare `cable_ready` as an explicit dependency of their app.

I hope this resolves your issue!

**Comment by gordysc** [comment]
@marcoroth Sure, that makes sense.  I get why it was moved to a peer dependency.   Thanks for the good discussion!  Already saw #351 , so I'm going to close this out.  Cheers!
