### PR TITLE
Fix fatal error in `stimulus_reflex:install` task with Rails 5.2

### LINKED ISSUE #367: `stimulus_reflex:install` fails to complete in Rails 5.2
# Bug Report

## Describe the bug

Fatal error in `stimulus_reflex:install` task in Rails 5.2.

## To Reproduce

1. Generate a fresh Rails app with 5.2
2. Go through the simple steps in the [setup guide](https://docs.stimulusreflex.com/setup#command-line-install)
3. `bundle exec rails stimulus_reflex:install` _mostly_ completes, but hits a fatal error and misses out a few bits of the install process

## Expected behavior

Setup succeeds in Rails 5.2

## Screenshots or reproduction

```
...snip
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
└─ stimulus_reflex@3.3.0
info All dependencies
├─ @rails/actioncable@6.0.3
├─ cable_ready@4.3.0
├─ form-serialize@0.7.2
├─ morphdom@2.6.1
└─ stimulus_reflex@3.3.0
Done in 6.24s.
mkdir -p /home/user/myproject/app/javascript/controllers
mkdir -p /home/user/myproject/app/reflexes
Updating /home/user/myproject/app/javascript/controllers/index.js
rails aborted!
NoMethodError: undefined method `module_parent' for Myproject::Application:Class
Did you mean?  module_eval
/home/user/myproject/bin/rails:9:in `<top (required)>'
/home/user/myproject/bin/spring:15:in `require'
/home/user/myproject/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => stimulus_reflex:install
(See full trace by running task with --trace)
```

The call to `#module_parent` in line 61 in `lib/stimulus_reflex/tasks/install.rake` causes the exception. Looks like the method is only available in `ActiveSupport` 6+.

### StimulusReflex

- Gem: 3.3.0
- Node package: 3.3.0

### External tools

Ruby 2.5.7
Rails 5.2.4.4
Node: 10.19.0

### Browser

- Browser FF
- Version 86

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
# Bug Fix

## Description

Fixes #367

Fixes a fatal error that stops the install task working in Rails 5.2.

The `#module_parent` method doesn't exist in Rails 5.2, but the direct alternatives are deprecated methods in 6.0... The method is only only being used to add a string of the current project's name as a prefix here, so we can switch it for something simple and backwards-compatible.

## Why should this be added

The install works in both versions and you can :fire: the section of the docs that says setting up SR in Rails 5.2 might require some manual hacks...

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing
- [x] This is not a documentation update

Please note that the best way to suggest changes or updates to the [documentation](https://docs.stimulusreflex.com) is to [join Discord](https://discord.gg/XveN625) and leave a note in the #docs channel. Any documentation updates posted as PRs cannot be accepted at this time. :heart:

### CODE REVIEW

**Comment by leastbad** [comment]
Nice work! And thanks for seeing this through.
